serviceAccount: projects/PROJECT_ID/serviceAccounts/sapient-office-489011-g9.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "golang:1.22"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        which go
        ls
        echo "Running Go tests and main program..."
        # export PATH="$PATH:/usr/local/go/bin"
        # go version
        # go test ./... || true
        # go run main.go
