serviceAccount: projects/sapient-office-489011-g9/serviceAccounts/sapient-office-489011-g9.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "golang:1.22"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        which go
        lserr
        echo "Running Go tests and main program..."
